import { HeaderAction } from '../../../core/components/header/header.component';

export const userActions: HeaderAction[] = [
  {
    key: 'edit',
    icon: 'edit',
    disabled: true,
  },
  {
    key: 'delete',
    icon: 'trash',
    disabled: true,
  },
  /*{
    key: 'search',
    icon: 'search',
    disabled: false,
  },*/
  {
    key: 'add',
    icon: 'plus',
    disabled: false,
  },
];

export const usersTableColumns = [
  { dataField: 'firstName', caption: 'Ime', width: 150 },
  { dataField: 'lastName', caption: 'Prezime', width: 150 },
  { dataField: 'email', caption: 'Email', width: 200 },
  { dataField: 'phone', caption: 'Telefon', width: 150 },
  { dataField: 'role', caption: 'Rola', width: 100 },
  { dataField: 'workplace', caption: 'Radno mjesto', width: 150 },
  { dataField: 'country', caption: 'Država', width: 150 },
  { dataField: 'city', caption: 'Grad', width: 150 },
];

export const mockUsers = [
  {
    id: 'a1b2c3d4e5f6g7h',
    firstName: 'Ivan',
    lastName: 'Horvat',
    email: 'ivan.horvat@example.com',
    phone: '+385 91 123 4567',
    role: ['Administrator'],
    workplace: 'Management',
    country: 'Croatia',
    city: 'Zagreb',
    gender: 'Male',
    username: 'ivan.horvat',
  },
  {
    id: 'x7y8z9w0v1u2t3s',
    firstName: 'Ana',
    lastName: 'Kovač',
    email: 'ana.kovac@example.com',
    phone: '+385 92 987 6543',
    role: ['User'],
    workplace: 'Development',
    country: 'Croatia',
    city: 'Split',
    gender: 'Female',
    username: 'ana.kovac',
  },
  {
    id: 'm4n5b6v7c8x9z0q',
    firstName: 'Marko',
    lastName: 'Babić',
    email: 'marko.babic@example.com',
    phone: '+385 91 234 5678',
    role: ['Administrator'],
    workplace: 'Marketing',
    country: 'Croatia',
    city: 'Rijeka',
    gender: 'Male',
    username: 'marko.babic',
  },
  {
    id: 'l9k8j7h6g5f4d3s',
    firstName: 'Petra',
    lastName: 'Novak',
    email: 'petra.novak@example.com',
    phone: '+385 95 876 5432',
    role: ['User'],
    workplace: 'Marketing',
    country: 'Croatia',
    city: 'Osijek',
    gender: 'Female',
    username: 'petra.novak',
  },
  {
    id: 'p1o2i3u4y5t6r7e',
    firstName: 'Luka',
    lastName: 'Vuković',
    email: 'luka.vukovic@example.com',
    phone: '+385 91 345 6789',
    role: ['Administrator'],
    workplace: 'Development',
    country: 'Croatia',
    city: 'Zadar',
    gender: 'Male',
    username: 'luka.vukovic',
  },
  {
    id: 'z0x9c8v7b6n5m4q',
    firstName: 'Maja',
    lastName: 'Pavić',
    email: 'maja.pavic@example.com',
    phone: '+385 92 654 3210',
    role: ['User'],
    workplace: 'Management',
    country: 'Croatia',
    city: 'Dubrovnik',
    gender: 'Female',
    username: 'maja.pavic',
  },
  {
    id: 'w1e2r3t4y5u6i7o',
    firstName: 'Filip',
    lastName: 'Radić',
    email: 'filip.radic@example.com',
    phone: '+385 98 543 2109',
    role: ['Administrator'],
    workplace: 'Development',
    country: 'Croatia',
    city: 'Varaždin',
    gender: 'Male',
    username: 'filip.radic',
  },
  {
    id: 'g6h5j4k3l2m1n0b',
    firstName: 'Marina',
    lastName: 'Knežević',
    email: 'marina.knezevic@example.com',
    phone: '+385 97 432 1098',
    role: ['User'],
    workplace: 'Design',
    country: 'Croatia',
    city: 'Pula',
    gender: 'Female',
    username: 'marina.knezevic',
  },
  {
    id: 'v8c7x6z5a4s3d2f',
    firstName: 'Nikola',
    lastName: 'Sertić',
    email: 'nikola.sertic@example.com',
    phone: '+385 96 321 0987',
    role: ['Administrator'],
    workplace: 'Management',
    country: 'Croatia',
    city: 'Šibenik',
    gender: 'Male',
    username: 'nikola.sertic',
  },
  {
    id: 't1y2u3i4o5p6a7s',
    firstName: 'Ivana',
    lastName: 'Tomić',
    email: 'ivana.tomic@example.com',
    phone: '+385 95 210 9876',
    role: ['User', 'Administrator'],
    workplace: 'Development',
    country: 'Croatia',
    city: 'Karlovac',
    gender: 'Female',
    username: 'ivana.tomic',
  },
  {
    id: 'f3g4h5j6k7l8m9n',
    firstName: 'Dario',
    lastName: 'Perić',
    email: 'dario.peric@example.com',
    phone: '+385 94 109 8765',
    role: ['User', 'Administrator'],
    workplace: 'Management',
    country: 'Croatia',
    city: 'Sisak',
    gender: 'Male',
    username: 'dario.peric',
  },
];

export const userRoles = ['Administrator', 'User'];

export const genderData = [
  { id: 'Female', value: 'Female' },
  { id: 'Male', value: 'Male' },
  { id: 'Other', value: 'Other' },
];

export const cityData = [
  { id: 'Zagreb', value: 'Zagreb' },
  { id: 'Split', value: 'Split' },
  { id: 'Rijeka', value: 'Rijeka' },
  { id: 'Osijek', value: 'Osijek' },
  { id: 'Zadar', value: 'Zadar' },
];

export const countryData = [{ id: 'Croatia', value: 'Croatia' }];

export const workplaceData = [
  { id: 'Design', value: 'Design' },
  { id: 'Management', value: 'Management' },
  { id: 'Marketing', value: 'Marketing' },
  { id: 'Development', value: 'Development' },
];
